apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend-service
spec:
  selector:
    app: todo-app
  ports:
    - name: backend-port
      port: 5000
      targetPort: 5000
      nodePort: 30007
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: todo-frontend-service
spec:
  selector:
    app: todo-app
  ports:
    - name: frontend-port
      port: 80  # Changed from 3000 to 80 for nginx
      targetPort: 80  # Changed from 3000 to 80 for nginx
      nodePort: 30008
  type: NodePort