name: Build and Deploy to Minikube

on:
  push:
    branches:
      - master  # Trigger the workflow on push to the main branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: spideyfati
        password: fati_2004  # Use secrets for credentials

    - name: Build and push Backend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./backend  # Adjust path to your backend code
        push: true
        tags: spideyfati/todo-backend:v2

    - name: Build and push Frontend Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend  # Adjust path to your frontend code
        push: true
        tags: spideyfati/todo-frontend:v2

    - name: Set up Minikube
      uses: medyagh/setup-minikube@latest

    - name: Deploy to Minikube
      run: |
        minikube status
        kubectl apply -f mongo.yaml
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
        kubectl get pods -A